### ISSUE TITLE
Direct support for modules?

### ISSUE THREAD

**Issue by cademirch** [Wytamma/snk-cli#15]
Hi @Wytamma, thanks for this awesome package! 

Curious if you have any thoughts on how to best implement a CLI for a workflow with modules? For example the "main" workflow produces a VCF, and I have multiple modules that do stuff with the VCF. Users may want to run the main workflow to make their VCF, but others may already have a VCF to start with. 

I haven't spent much time working on this, but came up with this:
```python
from pathlib import Path
from snk_cli import CLI
from snk_cli.config import SnkConfig

PARENT_DIR = Path(__file__).parent.parent

SNK_CONFIG_DIR = Path(PARENT_DIR / "snk_config")

snparcher = CLI(
    PARENT_DIR, snk_config=SnkConfig.from_path(Path(SNK_CONFIG_DIR / "main.yaml"))
)
snparcher_qc = CLI(
    Path(PARENT_DIR / "workflow" / "modules" / "qc" / "Snakefile"),
    snk_config=SnkConfig.from_path(Path(SNK_CONFIG_DIR / "qc.yaml")),
)
snparcher.register_group(snparcher_qc, name="qc", help="Run the qc workflow.")
```

I think this nicely covers my use case. However, I think it could be more intuitive for the the module to be a subcommand under the main run command. For example: `snparcher run qc <qc args>`

I think this may be fairly easy to implement by making the run command in the `CLI` class an attribute, then we could call `.register_group(snparcher_qc)` on the run command itself? Happy to look into this further if you think this is a good idea/right approach and are open to PRs!

**Comment by Wytamma** [comment]
Hi @cademirch,

Thanks for trying it out! Very cool solution to modules.

I think it will take a bit of redesign / refactoring to get the subcommands working. Part of the issue is that the RunApp is special and the commands of the RunApp are 'inherited' as commands of the parent app. Thats how cli.run.run becomes cli.run. So if you had cli.run.qc it'd become cli.qc as things are now. 

I'd be happy to accept PRs around this although I think it's tricky to get typer to play nice with default commands and subcommands. It won't be as simple as exposing the RunApp as you won't get assess to it until after it's initialised. 

Another option might be just to define multiple CLIs? E.g. keep `snparcher` and `snparcher_qc` and in pyproject.toml:
```
[project.scripts]
snparcher = "snparcher.cli:snparcher"
snparcher-qc = "snparcher.cli:snparcher_qc"
```
Then you'd avoid the weird nesting. 

Let me know if you really want `run qc` to work and we can work on some more solutions.

**Comment by cademirch** [comment]
Ah, that makes sense re: inheritance, thanks for the explanation. 

I wont pursue this further since what I have now seems to work and on second look it makes sense to keep modules as their own CLI object, but grouped under the main workflow. Should be more maintainable with separate snk.yamls. I will likely be back with more issues/questions as toy around, and am more than happy to help with open issues.

I also did do the multiple CLIs in the pyproject toml, but would like to keep everything under one command if possible.
